mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
]

mysite/cats/urls.py
from django.urls import path
from . views import MainView, CreateCats, UpdateCats, DeleteCats, ShowBreed, CreateBreed, UpdateBreed, DeleteBreed

app_name = "cats"
urlpatterns = [
    path("", MainView.as_view(), name="main_cats"),
    path("main/create/", CreateCats.as_view(), name="create_cats"),
    path("main/<int:pk>/update/", UpdateCats.as_view(), name="update_cats"),
    path("main/<int:pk>/delete/", DeleteCats.as_view(), name="delete_cats"),
    path("breed/", ShowBreed.as_view(), name="breed_list"),
    path("breed/create/", CreateBreed.as_view(), name="create_breed"),
    path("breed/<int:pk>/update/", UpdateBreed.as_view(), name="update_breed"),
    path("breed/<int:pk>/delete/", DeleteBreed.as_view(), name="delete_breed"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import os
from django.views.static import serve
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
# from django.conf.urls import url

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

# add path to all webapp in main path of project
urlpatterns = [
    path("ads/", include("ads.urls")),
    path("cats/", include("cats.urls")),
    path("autos/", include("autos.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("hello/", include("hello.urls")),
    path("", TemplateView.as_view(template_name="home/main.html")),
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/cats/models.py
from django.db import models

# Create your models here.

# breed class
class Breed(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

# cat class
class Cat(models.Model):
    nickname = models.CharField(max_length=200)
    weight = models.FloatField()
    breed = models.ForeignKey("Breed", on_delete=models.CASCADE, null=False)
    foods = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.nickname

mysite/cats/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Cat, Breed

# Create your views here.
class ShowBreed(LoginRequiredMixin, View):
    def get(self, request):
        brd = Breed.objects.all()

        ctx = {"breed_list": brd}
        return render(request, "cats/breed_list.html", ctx)

class CreateBreed(LoginRequiredMixin, CreateView):
    model = Breed
    fields = "__all__"
    success_url = reverse_lazy("cats:breed_list")

class UpdateBreed(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = "__all__"
    success_url = reverse_lazy("cats:breed_list")

class DeleteBreed(LoginRequiredMixin, DeleteView):
    model = Breed
    fields = "__all__"
    success_url = reverse_lazy("cats:breed_list")

class MainView(LoginRequiredMixin, View):
    def get(self, request):
        cat_all = Cat.objects.all()
        breed_c = Breed.objects.all().count()

        ctx = {"cat_list": cat_all, "breed_count":breed_c}
        return render(request, "cats/cat_list.html", ctx)

class CreateCats(LoginRequiredMixin, CreateView):
    model = Cat
    fields = "__all__"
    success_url = reverse_lazy("cats:main_cats")

class UpdateCats(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = "__all__"
    success_url = reverse_lazy("cats:main_cats")

class DeleteCats(LoginRequiredMixin, DeleteView):
    model = Cat
    fields = "__all__"
    success_url = reverse_lazy("cats:main_cats")

mysite/cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Breed</h1>
<p>Sure!! You want to delete breed: {{ breed }} ?</p>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>

{% endblock %}

mysite/cats/templates/cats/breed_list.html
{% extends "base_bootstrap.html" %}

{% block content %}

{% if breed_list %}
    <h1>List of breed:</h1>
    <ul>
        {% for breed in breed_list %}
        <li>
            {{ breed.name}} <br>
            <a href="{% url 'cats:update_breed' breed.id %}">Update</a> |
            <a href="{% url 'cats:delete_breed' breed.id %}">Delete</a>
        </li>
        {% endfor %}
    </ul>

{% else %}
    <h1>There is no breed.</h1>

{% endif %}

<a href="{% url 'cats:create_breed' %}">Create new breed</a><br>
<a href="{% url 'cats:breed_list' %}">View breeds</a><br>

<a href="{% url 'cats:main_cats' %}">View cats</a>
{% endblock %}

mysite/cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete cat</h1>
<p>Sure!! You want to delete cat: {{ cat }} ?</p>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>

{% endblock %}

mysite/cats/templates/cats/cat_list.html
{% extends "base_bootstrap.html" %}

{% block content %}

{% if cat_list %}
    <h1>List of cats:</h1>
    <ul>
        {% for cat in cat_list %}
        <li>
            Nickname: {{ cat.nickname }} <br>
            Breed: {{ cat.breed.name }} <br>
            Weight: {{ cat.weight }} <br>
            <a href="{% url 'cats:update_cats' cat.id %}">Update</a> |
            <a href="{% url 'cats:delete_cats' cat.id %}">Delete</a>
        </li>
        {% endfor %}
    </ul>

{% else %}
    <h1>There is no cats.</h1>

{% endif %}

{% if breed_count > 0 %}
    <p><a href="{% url 'cats:create_cats' %}">Add a cat</a></p>
{% else %}
    <p>First create new breed!</p>
{% endif %}

<a href="{% url 'cats:breed_list' %}">View breeds</a> |
<a href="{% url 'cats:create_breed' %}">Add a breed</a>
{% endblock %}